# Generated by Django 4.0.3 on 2022-03-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('storyline', models.TextField()),
                ('image', models.ImageField(upload_to='movies')),
                ('genre', models.CharField(choices=[('AC', 'Action'), ('AD', 'Adventure'), ('AN', 'Animation'), ('BI', 'Biography'), ('CO', 'Comedy'), ('DO', 'Documentary'), ('DR', 'Drama'), ('FA', 'Family'), ('HI', 'History'), ('HO', 'Horror'), ('MY', 'Mystery'), ('RO', 'Romance'), ('TH', 'Thriller'), ('WA', 'War')], max_length=2)),
                ('language', models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('GE', 'German'), ('RU', 'Russian')], max_length=2)),
                ('status', models.CharField(choices=[('RA', 'Recently Added'), ('MW', 'Most Watched'), ('TR', 'Top Rated')], max_length=2)),
                ('director', models.CharField(max_length=100)),
                ('duration', models.TimeField()),
                ('release_date', models.DateField()),
            ],
        ),
    ]
