# Generated by Django 4.0.3 on 2022-04-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_user_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
